spring:
  profiles:
    active:
     - dev
     
---
spring:
  profiles: dev
  application:
    name: servicecloud-config-xu-dev
    
---
spring:
  profiles: test
  application:
    name: servicecloud-config-xu-test
